# Generated by Django 3.2.25 on 2024-04-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle',
            old_name='category',
            new_name='enterprise',
        ),
        migrations.AddField(
            model_name='cattle',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle.stocktype'),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattle.breed'),
        ),
    ]
