# Generated by Django 3.2.25 on 2024-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_auto_20240410_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattle',
            options={'verbose_name_plural': 'Cattle'},
        ),
        migrations.AddField(
            model_name='cattle',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cattle',
            name='tag',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
